version: "3.9"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.76.1
    command:
      - "--config=/etc/otel-collector-config.yaml"
    volumes:
      - "$PWD/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml"
    ports:
      - "4317:4317"
    networks:
      - local
    depends_on:
      - prometheus
      - tempo

  prometheus:
    image: prom/prometheus:v2.43.0
    volumes:
      - "$PWD/prometheus/prometheus.yaml:/etc/prometheus.yaml"
    command:
      - "--config.file=/etc/prometheus.yaml"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--storage.tsdb.retention.time=1h"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
      - "--web.route-prefix=/"
      - "--web.enable-remote-write-receiver"
    networks:
      - local

  tempo:
    image: grafana/tempo:main-3f562c6
    command:
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - "$PWD/tempo/tempo.yaml:/etc/tempo.yaml"
    networks:
      - local

  grafana:
    image: grafana/grafana:9.5.1
    volumes:
      - "$PWD/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml"
    ports:
      - "3000:3000"
    environment:
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_BASIC_ENABLED=false"
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_FEATURE_TOGGLES_ENABLE=traceqlEditor"
    networks:
      - local
    depends_on:
      - prometheus
      - tempo

networks:
  local:
    driver: bridge
